# -*- coding: utf-8 -*-
"""Advanced AI Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoraywBfRQRmFZs7bF7fxI2ILfOrgGXV
"""

!pip install h5py
!pip install typing-extensions
!pip install wheel

!pip install Flask pyngrok mistralai

import os
from flask import Flask, request, render_template_string, jsonify
from pyngrok import ngrok
from mistralai.client import Mistral
from getpass import getpass

mistral_api_key = getpass('Please enter your Mistral API key: ')
ngrok_auth_token = getpass('Please enter your ngrk auth token: ')

from flask import Flask, request, render_template_string, jsonify

client = Mistral(api_key = mistral_api_key)
app = Flask(__name__)
port = 8000

html = """

<html>
  <title> Chatbot </title>
  <style> .user { color: blue; } </style>

  <body>
    <div id = "chatbot"></div>
    <input id = "input" placeholder = "Ask me anything">
    <button onclick="send()"> Send </button>

    <script>
      function send(){
        const msg = document.getElementById("input").value;
        if(!msg) return;

        add("You", msg, 'user')
        document.getElementById("input").value = ''
        fetch('./get_response', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({msg: msg})})
        .then(res => res.json()).then(data => add('Bot', data.response, 'bot'))
      }

      function add(sender, msg, cls){
        const div = document.createElement('div')
        div.className = `msg ${cls}`
        div.textContent = `${sender} : ${msg}`
        document.getElementById('chatbot').appendChild(div)
        document.getElementById('chatbot').scrollTop = document.getElementById('chatbot').scrollHeight;

      }
    </script>
  </body>
</html>
"""

@app.route('/')
def index():
  return render_template_string(html)


@app.route('/get_response', methods=["POST"])
def get_response():
    user_input = request.json.get('msg', '')

    if not user_input.strip():
        return jsonify({'response': 'Empty message!'})

    response = client.chat.complete(
        model="mistral-large-latest",
        messages=[
            {"role": "user", "content": user_input}
        ]
    )

    return jsonify({'response': response.choices[0].message.content})


if(__name__ == "__main__"):
  ngrok.set_auth_token(ngrok_auth_token)
  public_url = ngrok.connect(port)
  print("Chatbotunn running at :" + str(public_url))
  app.run(port = port)

"""After running the above cell, please re-execute the import cell with `from mistralai.client import MistralClient` to confirm the fix."""